stages:
  make_dataset:
    cmd: >
      python src/data_processing/make_dataset.py data/raw data/interim
    deps:
      - data/raw
      - src/data_processing/make_dataset.py
    params:
      - config/params.json:
          - '*' 
    outs:
      - data/interim/merged.csv

  validate:
    cmd: >
      python src/data_processing/validate.py
      --schema config/schema.json
      --report reports/validation_report.json
      data/interim/merged.csv
    deps:
      - config/schema.json
      - data/interim/merged.csv
      - src/data_processing/validate.py
    outs:
      - reports/validation_report.json

  build_features:
    cmd: >
      python src/features/build_features.py
      --input-file data/interim/merged.csv
      --output-dir data/processed
      --manifest manifest_features.json
    deps:
      - data/interim/merged.csv
      - src/features/build_features.py
    params:
      - config/params.json:
          - '*'
    outs:
      - data/processed/features.csv
      - manifest_features.json
