stages:
  make_dataset:
    cmd: python src/data_processing/make_dataset.py data/raw data/interim
    deps:
    - data/raw
    - src/data_processing/make_dataset.py
    outs:
    - data/interim/merged.csv
  