stages:
  make_dataset:
    cmd: python src/data_processing/make_dataset.py data/raw data/interim
    deps:
    - data/raw
    - src/data_processing/make_dataset.py
    outs:
    - data/interim/merged.csv
  validate:
    cmd: python src/data_processing/validate.py data/interim/merged.csv --schema
      config/schema.json --report-path reports/validation_report.json
    deps:
    - config/schema.json
    - data/interim/merged.csv
    - src/data_processing/validate.py
    outs:
    - reports/validation_report.json
  build_features:
    cmd: python src/features/build_features.py --input-file 
      data/interim/merged.csv --output-dir data/processed --manifest 
      manifest_features.json
    deps:
    - data/interim/merged.csv
    - src/features/build_features.py
    outs:
    - data/processed/features.csv
    - manifest_features.json
