[server]
headless = true
enableCORS = true  # Keep this enabled for security
enableXsrfProtection = true  # Keep this enabled for security


[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = false
port = 8501



[runner]
magicEnabled = false